proyecto_dc_hector/urls.py
from django.urls import path
from decharla import views
from django.contrib.auth.views import LoginView

urlpatterns = [
    # Ruta para la página de inicio
    path('', views.home, name='home'),

    # Ruta para hacer login
    path('accounts/login/', LoginView.as_view(template_name='login.html'), name='login'),
    # ruta lista de camaras
    path('cameras/', views.camera_list, name='camera_list'),
    # ruta para la camara estatica
    path('cameras/<str:id>/', views.camera_detail, name='camera_detail'),
    # ruta para la camara dinamica
    path('cameras/<str:id>-dyn', views.camera_image, name='camera_image'),
    # ruta para los comentarios
    path('comentario/', views.camera_comments, name='camera_comments'),
    
    # ruta para actualizar los comentarios
    path('cameras/<str:camera_id>/comments/', views.get_comments_json, name='get_comments_json'),
    
    # Ruta para hacer registro
    path('accounts/registro/', views.registro_view, name='registro'),
    
    # Ruta para el logout
    path('logout/', views.logout_view, name='logout'),
    
    # Rutas adicionales para el menú horizontal
    path('configuration/', views.configuration, name='configuration'),
    path('help/', views.help_page, name='help'),
    path('admin/', views.admin_panel, name='admin'),
]

decharla/models.py
from django.contrib.auth.models import User
from django.db import models
from django.db.models.signals import post_save
from django.dispatch import receiver


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    chat_name = models.CharField(max_length=100, blank=True, null=True)

    def __str__(self):
        return self.user.username

    def save(self, *args, **kwargs):
        # Si chat_name no está establecido, usar el nombre de usuario como valor predeterminado
        if not self.chat_name:
            self.chat_name = self.user.username
        super(Profile, self).save(*args, **kwargs)

class Camera(models.Model):
    identifier = models.CharField(max_length=100, unique=True)
    name = models.CharField(max_length=100)
    location = models.CharField(max_length=100)
    image_url = models.URLField()

    def __str__(self):
        return self.name

class Comment(models.Model):
    camera = models.ForeignKey(Camera, on_delete=models.CASCADE, related_name='comments')
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    text = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    image_url = models.URLField(max_length=200, blank=True, null=True)  # Campo opcional para la URL de la imagen

    def __str__(self):
        return f'Comment on {self.camera.name} by {self.author.username} at {self.created_at}'


@receiver(post_save, sender=User)
def create_user_profile(sender, instance, created, **kwargs):
    if created:
        Profile.objects.create(user=instance)

decharla/forms.py
from django import forms
from .models import Comment, Profile, Camera
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

class ProfileForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ['chat_name']

class CameraIDForm(forms.Form):
    camera_id = forms.IntegerField(label="Enter Camera ID", min_value=0)

class CommentForm(forms.ModelForm):
    text = forms.CharField(widget=forms.Textarea(attrs={'rows': 4}), required=True)
    image_url = forms.URLField(required=False)  # Permitir a los usuarios especificar o modificar la URL de la imagen

    class Meta:
        model = Comment
        fields = ['camera', 'text', 'image_url']

    def clean_text(self):
        text = self.cleaned_data['text']
        if not text.strip():
            raise forms.ValidationError("El contenido del comentario no puede estar vacío.")
        return text 

class UserRegistrationForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['password1', 'password2']

decharla/views.py
import requests
import xml.etree.ElementTree as ET
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.contrib.auth import login, authenticate, logout
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.views import LoginView  # Importar la vista de inicio de sesión
from django.http import HttpResponseForbidden, HttpResponse
from django.contrib import messages
from .models import Camera, Comment, Profile
from .forms import UserRegistrationForm, CommentForm, ProfileForm, CameraIDForm
from django.utils.timezone import now
from django.utils import timezone
from django.db.models import Q  # Importa Q para consultas complejas
from django.urls import reverse
from django.core.paginator import Paginator
from django.http import JsonResponse

# Vista para mostrar todas las habitaciones disponibles
@login_required
def home(request):
    comments_list = Comment.objects.select_related('camera').order_by('-created_at')
    paginator = Paginator(comments_list, 10)  # Muestra 10 comentarios por página

    page_number = request.GET.get('page')
    comments = paginator.get_page(page_number)
    if request.method == 'POST':
        if 'logout' in request.POST:
            logout(request)
            return redirect('login')  # Redirige a la página de login después del logout
    return render(request, 'home.html', {'comments': comments})

@login_required
def configuration(request):
    try:
        profile = request.user.profile  # Obtener el perfil del usuario actual
    except Profile.DoesNotExist:
        # Si el perfil no existe, crearlo
        profile = Profile.objects.create(user=request.user)
    if request.method == 'POST':
        form = ProfileForm(request.POST, instance=profile)
        if form.is_valid():
            form.save()
            return redirect('home')  # O cualquier otra página después de guardar la configuración
    else:
        form = ProfileForm(instance=profile)
    return render(request, 'configuration.html', {'form': form})

# Vista para mostrar la página de ayuda
@login_required
def help_page(request):
    return render(request, 'help.html')


@login_required
def camera_comments(request):
    if request.method == 'POST':
        form = CameraIDForm(request.POST)
        if form.is_valid():
            camera_id = form.cleaned_data['camera_id']
            return redirect('camera_detail', id=camera_id)
    else:
        form = CameraIDForm()

    return render(request, 'enter_camera_id.html', {
        'form': form
    })

def fetch_cameras():
    url = 'https://gitlab.eif.urjc.es/cursosweb/2023-2024/final-teveo/-/raw/main/listado1.xml'
    response = requests.get(url)
    root = ET.fromstring(response.content)

    for camera in root.findall('camara'):
        identifier = camera.find('id').text
        name = camera.find('lugar').text
        location = camera.find('coordenadas').text
        image_url = camera.find('src').text

        # Check if camera already exists, if not create a new one
        obj, created = Camera.objects.update_or_create(
            identifier=identifier,
            defaults={'name': name, 'location': location, 'image_url': image_url}
        )

def fetch_cameras_listado2():
    url = 'https://gitlab.eif.urjc.es/cursosweb/2023-2024/final-teveo/-/raw/main/listado2.xml'
    response = requests.get(url)
    root = ET.fromstring(response.content)

    for cam in root.findall('cam'):
        identifier = cam.get('id')
        image_url = cam.find('url').text
        name = cam.find('info').text
        latitude = cam.find('place/latitude').text
        longitude = cam.find('place/longitude').text
        location = f"Lat: {latitude}, Lon: {longitude}"

        # Check if camera already exists, if not create a new one
        obj, created = Camera.objects.update_or_create(
            identifier=identifier,
            defaults={'name': name, 'location': location, 'image_url': image_url}
        )

@login_required
def camera_list(request):
    fetch_cameras()  # Optionally call this function to update cameras
    fetch_cameras_listado2()  # Updates the camera data from Listado 2
    query = request.GET.get('q')
    if query:
        cameras = Camera.objects.filter(
            Q(identifier__icontains=query) | Q(name__icontains=query)
        )
    else:
        cameras = Camera.objects.all()

    return render(request, 'camera_list.html', {'cameras': cameras, 'query': query})

@login_required
def camera_image(request, id):
    camera = get_object_or_404(Camera, identifier=id)
    comments = Comment.objects.filter(camera=camera).order_by('-created_at')
    form = CommentForm()

    if request.method == 'POST':
        form = CommentForm(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.camera = camera
            comment.author = request.user
            comment.save()

            # Si es una solicitud HTMX, actualizar solo la parte de comentarios
            if "HX-Request" in request.headers:
                return render(request, 'comments_list.html', {'comments': comments, 'camera': camera})

            # Si no es HTMX, redirigir para recargar la página completa
            return redirect('camera_image', id=camera.identifier)
    
    context = {
        'camera': camera,
        'comments': comments,
        'form': form
    }

    # Si es una solicitud HTMX para la imagen, responder solo con la imagen actualizada
    if "HX-Request" in request.headers:
        print("Respondiendo a una solicitud HTMX para la imagen")  # Mensaje de depuración
        return HttpResponse(f'<img src="{camera.image_url}" class="card-img-top" alt="Camera Image" style="width:100%; height:auto;">')

    return render(request, 'camera_image.html', context)

@login_required
def get_comments_json(request, camera_id):
    comments = Comment.objects.filter(camera__identifier=camera_id).order_by('-created_at')
    comments_data = [{'author': c.author.username, 'text': c.text, 'created_at': c.created_at.strftime('%Y-%m-%d %H:%M:%S')} for c in comments]
    return JsonResponse(comments_data, safe=False)
    
@login_required
def camera_detail(request, id):
    camera = get_object_or_404(Camera, identifier=id)
    if request.method == 'POST':
        form = CommentForm(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.camera = camera
            comment.author = request.user
            comment.save()
            return redirect('camera_detail', id=camera.identifier)
    else:
        form = CommentForm()
    comments = Comment.objects.filter(camera=camera).order_by('-created_at')
    return render(request, 'camera_detail.html', {'camera': camera, 'comments': comments, 'form': form})

# Vista para mostrar el panel de administrador
@login_required
def admin_panel(request):
    if request.user.is_superuser:
        # Aquí implementa la lógica para el panel de administrador
        return render(request, 'admin_panel.html')
    else:
        return HttpResponseForbidden("Acceso denegado. Debes ser un administrador para ver esta página.")

# Vista para el deslogueo del usuario
def logout_view(request):
    logout(request)
    return redirect('login')  # Redirige a la página de inicio de sesión después del logout
    
# Vista para el registro de usuario
def registro_view(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            raw_password = form.cleaned_data.get('password1')
            user = authenticate(username=username, password=raw_password)
            login(request, user)
            return redirect('home')
        else:
            # Agregar mensajes de error al contexto
            for field, errors in form.errors.items():
                for error in errors:
                    messages.error(request, f"{field}: {error}")
    else:
        form = UserCreationForm()
    return render(request, 'registro.html', {'form': form})

# Vista para el inicio de sesión utilizando la vista de LoginView proporcionada por Django
def login_view(request):
    return LoginView.as_view()(request)


decharla/templates/camera_detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Camera Details</title>
    <!-- Incluir Bootstrap CSS -->
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" rel="stylesheet">
    <!-- Aquí puedes incluir tus estilos personalizados -->
    {% load static %}
	<link rel="shortcut icon" href="{% static 'favicon.ico' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'styles.css' %}">
</head>
<body class="bg-primary text-dark">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <div class="title-container py-4">
                    <h1 class="text-center">{{ camera.name }}</h1>
                    <nav class="menu text-center">
                        <ul class="list-inline">
                            <li class="list-inline-item"><a href="{% url 'home' %}">Home</a></li>
                            <li class="list-inline-item"><a href="{% url 'configuration' %}">Configuration</a></li>
                            <li class="list-inline-item"><a href="{% url 'help' %}">Help</a></li>
                            <li class="list-inline-item"><a href="{% url 'camera_list' %}">Camera List</a></li>
                            {% if is_admin %}
                                <li class="list-inline-item"><a href="{% url 'admin' %}">Admin</a></li>
                            {% endif %}
                        </ul>
                    </nav>
                </div>
            </div>
        </div>

        <div class="row">
            <div class="col-md-12">
                <div class="card mb-4">
                    <img src="{{ camera.image_url }}" class="card-img-top" alt="Camera Image" style="width:100%; height:auto;">
                    <div class="card-body">
                        <h5 class="card-title">{{ camera.location }}</h5>
                        <p class="card-text">Explore live feed and comments below!</p>
                    </div>
                </div>
            </div>
        </div>

        <div class="row">
            <div class="col-md-12">
                <h2>Comments</h2>
                <div class="list-group">
                    {% for comment in camera.comments.all %}
                    <div class="list-group-item flex-column align-items-start">
                        <div class="d-flex w-100 justify-content-between">
                            <h5 class="mb-1">{{ comment.author.username }}</h5>
                            <small>{{ comment.created_at }}</small>
                        </div>
                        <p class="mb-1">{{ comment.text }}</p>
                        {% if comment.image_url %}
                        <img src="{{ comment.image_url }}" alt="Attached Image" style="width:100px; height:auto;">
                        {% endif %}
                    </div>
                    {% empty %}
                    <p class="text-muted">No comments yet.</p>
                    {% endfor %}
                </div>

                <!-- Comment Submission Form -->
                <div class="mt-4">
                    <h2>Leave a Comment</h2>
                    <form method="post">
                        {% csrf_token %}
                        <input type="hidden" name="camera" value="{{ camera.id }}">
                        <div class="form-group">
                            <label for="text">Your Comment:</label>
                            <textarea class="form-control" id="text" name="text" rows="3" required></textarea>
                        </div>
                        <button type="submit" class="btn btn-primary">Post Comment</button>
                    </form>
                </div>
            </div>
        </div>
    </div>

    <!-- Incluir Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.5.4/dist/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
</body>
</html>

decharla/templates/camera_image.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Camera Image</title>
    <!-- Bootstrap CSS -->
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" rel="stylesheet">
    <!-- Custom Styles -->
    {% load static %}
	<link rel="shortcut icon" href="{% static 'favicon.ico' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'styles.css' %}">
    <!-- HTMX -->
    <script src="https://unpkg.com/htmx.org"></script>
</head>
<body class="bg-primary text-dark">
    <div class="container">
        <!-- Title and Navigation -->
        <div class="row">
            <div class="col-md-12">
                <div class="title-container py-4">
                    <h1 class="text-center">{{ camera.name }}</h1>
                    <nav class="menu text-center">
                        <ul class="list-inline">
                            <li class="list-inline-item"><a href="{% url 'home' %}">Home</a></li>
                            <li class="list-inline-item"><a href="{% url 'configuration' %}">Configuration</a></li>
                            <li class="list-inline-item"><a href="{% url 'help' %}">Help</a></li>
                            <li class="list-inline-item"><a href="{% url 'camera_list' %}">Camera List</a></li>
                            {% if is_admin %}
                                <li class="list-inline-item"><a href="{% url 'admin' %}">Admin</a></li>
                            {% endif %}
                        </ul>
                    </nav>
                </div>
            </div>
        </div>

        <!-- Camera Image with HTMX Trigger -->
        <div class="row">
            <div class="col-md-12">
                <img id="live-camera-image" hx-get="{% url 'camera_image' camera.identifier %}" hx-trigger="every 30s, load" src="{{ camera.image_url }}" class="card-img-top" alt="Camera Image" style="width:100%; height:auto;">
            </div>
        </div>

        <!-- Comments Section -->
        <div class="row">
            <div class="col-md-12">
                <h2>Comments</h2>
				 <div id="comments-container">
					<!-- Los comentarios se cargarán aquí dinámicamente -->
				 </div>
                <!-- Button to Camera Details for Commenting -->
                <div class="mt-4">
                    <a href="{% url 'camera_detail' camera.identifier %}" class="btn btn-primary">Go to Details to Comment</a>
                </div>
            </div>
        </div>
    </div>
	<!-- JavaScript to force image refresh -->
    <script>
	document.addEventListener("DOMContentLoaded", function() {
		const img = document.getElementById('live-camera-image');
		const commentsContainer = document.getElementById('comments-container');
		const refreshRate = 30000; // 30 segundos expresados en milisegundos

		// Función para actualizar la imagen de la cámara
		function updateImage() {
			const src = img.getAttribute('src');
			const newSrc = src.split('?')[0] + '?time=' + new Date().getTime();
			img.setAttribute('src', newSrc);
		}

		// Iniciar la actualización periódica de la imagen de la cámara
		setInterval(updateImage, refreshRate);
	
		// Utiliza HTMX para actualizar el contenedor de comentarios
		function updateComments() {
			// Esto presupone que HTMX ya está configurado correctamente en el div de comentarios
			htmx.trigger(commentsContainer, 'refresh');
		}

		// Iniciar la actualización periódica de los comentarios
		setInterval(updateComments, refreshRate);
	});
	</script>
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
	<script>
	$(document).ready(function() {
		function fetchComments() {
			$.ajax({
				url: '{% url "get_comments_json" camera.identifier %}',
				type: 'GET',
				dataType: 'json',
				success: function(data) {
					var commentsContainer = $('#comments-container');
					commentsContainer.empty(); // Limpia los comentarios antiguos
					data.forEach(function(comment) {
						var commentHtml = `<div class="list-group-item flex-column align-items-start">
							<div class="d-flex w-100 justify-content-between">
								<h5 class="mb-1">${comment.author}</h5>
								<small class="text-muted">${comment.created_at}</small>
							</div>
							<p class="mb-1">${comment.text}</p>
						</div>`;
						commentsContainer.append(commentHtml); // Añade cada comentario al contenedor
					});
				},
				error: function() {
					console.log('Error fetching comments');
				}
			});
		}
		setInterval(fetchComments, 30000); // Actualiza los comentarios cada 30 segundos
		fetchComments(); // También carga los comentarios al cargar la página
	});
	</script>
    <!-- Incluir Bootstrap JS -->
    
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.5.4/dist/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
</body>
</html>

decharla/templates/camera_list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Camera List</title>
    <!-- Incluir Bootstrap CSS -->
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" rel="stylesheet">
    <!-- Aquí puedes incluir tus estilos personalizados -->
    {% load static %}
    <link rel="shortcut icon" href="{% static 'favicon.ico' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'styles.css' %}">
</head>
<body class="bg-primary text-dark">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <div class="title-container py-4">
                    <h1 class="text-center">Camera List</h1>
                    <nav class="menu text-center">
                        <ul class="list-inline">
                            <li class="list-inline-item"><a href="{% url 'home' %}">Home</a></li>
                            <li class="list-inline-item"><a href="{% url 'camera_list' %}">Camera List</a></li>
                            <li class="list-inline-item"><a href="{% url 'configuration' %}">Configuration</a></li>
                            <li class="list-inline-item"><a href="{% url 'help' %}">Help</a></li>
                            {% if is_admin %}
                                <li class="list-inline-item"><a href="{% url 'admin' %}">Admin</a></li>
                            {% endif %}
                        </ul>
                    </nav>
                </div>
            </div>
        </div>

        <!-- Formulario de Búsqueda -->
        <div class="row mb-4">
            <div class="col-md-12">
                <form method="GET" action="{% url 'camera_list' %}">
                    <div class="input-group">
                        <input type="text" name="q" class="form-control" placeholder="Search by ID or Name" value="{{ query|default_if_none:'' }}">
                        <div class="input-group-append">
                            <button type="submit" class="btn btn-secondary">Search</button>
                        </div>
                    </div>
                </form>
            </div>
        </div>

        <div class="row">
            <div class="col-md-12">
                <div class="table-responsive">
                    <table class="table table-bordered">
                        <thead class="thead-dark">
                            <tr>
                                <th scope="col">ID</th>
                                <th scope="col">Name</th>
                                <th scope="col">Location</th>
                                <th scope="col">Image</th>
                                <th scope="col">Actions</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for camera in cameras %}
                            <tr>
                                <td>{{ camera.identifier }}</td>
                                <td>{{ camera.name }}</td>
                                <td>{{ camera.location }}</td>
                                <td><img src="{{ camera.image_url }}" alt="Camera Image" style="width: 100px; height: auto;"></td>
                                <td>
                                    <a href="{% url 'camera_detail' camera.identifier %}" class="btn btn-primary">View Details</a>
                                    <a href="{% url 'camera_image' camera.identifier %}" class="btn btn-secondary">View Live</a>
                                </td>
                            </tr>
                            {% empty %}
                            <tr><td colspan="5">No cameras found.</td></tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>

    <!-- Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.5.4/dist/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
</body>
</html>

decharla/templates/comments_list.html
<!-- comments_list.html -->
<div class="list-group">
    {% for comment in comments %}
    <div class="list-group-item flex-column align-items-start">
        <div class="d-flex w-100 justify-content-between">
            <h5 class="mb-1">{{ comment.author.username }}</h5>
            <small class="text-muted">{{ comment.created_at|date:"N j, Y, P" }}</small>
        </div>
        <p class="mb-1">{{ comment.text }}</p>
        {% if comment.image_url %}
        <div>
            <img src="{{ comment.image_url }}" alt="Attached Image" class="img-fluid" style="max-height: 200px;">
        </div>
        {% endif %}
    </div>
    {% empty %}
    <div class="list-group-item">
        <p class="text-muted">No comments yet. Be the first to comment!</p>
    </div>
    {% endfor %}
</div>

decharla/templates/configuration.html
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Configuración</title>
    <!-- Incluir Bootstrap CSS -->
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" rel="stylesheet">
    <!-- Aquí puedes incluir tus estilos personalizados -->
    {% load static %}
	<link rel="shortcut icon" href="{% static 'favicon.ico' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'styles.css' %}">
</head>
<body>
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <h1 class="mt-4">Configuración de Alias</h1>
                <form method="post" class="mt-4">
                    {% csrf_token %}
                    <div class="form-group">
                        <label for="id_chat_name">Alias:</label>
                        {{ form.chat_name }}
                    </div>
                    <button type="submit" class="btn btn-primary">Guardar</button>
                </form>
            </div>
        </div>
    </div>

    <!-- Incluir Bootstrap JS (opcional) -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.5.4/dist/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
</body>
</html>

decharla/templates/enter_camera_id.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Enter Camera ID</title>
    <!-- Incluir Bootstrap CSS -->
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" rel="stylesheet">
    <!-- Estilos personalizados -->
    {% load static %}
	<link rel="shortcut icon" href="{% static 'favicon.ico' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'styles.css' %}">
</head>
<body class="bg-primary text-dark">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <div class="title-container py-4">
                    <h1 class="text-center">Enter Camera ID</h1>
                    <nav class="menu text-center">
                        <ul class="list-inline">
                            <li class="list-inline-item"><a href="{% url 'home' %}">Home</a></li>
                            <li class="list-inline-item"><a href="{% url 'configuration' %}">Configuration</a></li>
                            <li class="list-inline-item"><a href="{% url 'help' %}">Help</a></li>
                            {% if is_admin %}
                                <li class="list-inline-item"><a href="{% url 'admin' %}">Admin</a></li>
                            {% endif %}
                        </ul>
                    </nav>
                </div>
            </div>
        </div>
        
        <div class="row justify-content-center">
            <div class="col-md-6">
                <form method="post" class="form-horizontal mt-5">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <div class="form-group">
                        <button type="submit" class="btn btn-success">Submit</button>
                    </div>
                </form>
            </div>
        </div>
    </div>

    <!-- Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.5.4/dist/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
</body>
</html>